twig:
  form_themes: ["bootstrap_5_layout.html.twig"]
  file_name_pattern: "*.twig"
  globals:
        csp: "default-src 'self'; frame-src 'self' https://www.youtube.com;"

when@test:
  twig:
    strict_variables: true
